# Imports

In [1]:
import os
import time
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.decomposition import PCA
from sklearn.random_projection import GaussianRandomProjection
from sklearn.metrics.pairwise import cosine_similarity
from IPython.display import display

In [14]:
import requests

# Choose a completely unique password-like topic name here
topic_name = "aysel_tfe_server_9988"

# Configuration

In [2]:

# --- Configuration ---
CURRENT_DATASET = "Flickr8k"
DATA_DIR = os.path.join(os.getcwd(), 'TFE_Data')
IMAGE_DIR = os.path.join(DATA_DIR, "Flickr8k", "Images", "Flicker8k_Dataset")
IMAGE_PATHS = sorted(glob.glob(os.path.join(IMAGE_DIR, "*.jpg")))

DIMENSIONS_TO_TEST = [512, 256, 128, 64, 32, 16]

print(f"Environment ready. Target Dataset: {CURRENT_DATASET}")

Environment ready. Target Dataset: Flickr8k

# Data Loading

In [3]:
def load_raw_matrix(modality, model_name):
    """Loads the pre-computed RAW embedding matrix."""
    file_path = os.path.join(DATA_DIR, f"X_{modality}_{model_name}_raw_{CURRENT_DATASET}.npy")
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Matrix not found at {file_path}")
    return np.load(file_path)

In [4]:
def normalize_matrix(matrix):
    """L2 Normalization for Cosine Similarity."""
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    return matrix / np.where(norms == 0, 1e-9, norms)

# Dimension Reducers

In [6]:
def apply_pca(raw_matrix, target_dim):
    return PCA(n_components=target_dim).fit_transform(raw_matrix)

In [7]:
def apply_grp(raw_matrix, target_dim):
    return GaussianRandomProjection(n_components=target_dim).fit_transform(raw_matrix)

# Green AI: Retrieval time analysis

In [8]:
def measure_retrieval_speed(matrix, num_trials=100):
    """Measures average milliseconds to query the entire database."""
    norm_mat = normalize_matrix(matrix)
    query = norm_mat[0].reshape(1, -1) # Random query
    
    start_time = time.perf_counter()
    for _ in range(num_trials):
        sims = cosine_similarity(query, norm_mat)
        _ = np.argsort(sims[0])[::-1]
    end_time = time.perf_counter()
    
    return ((end_time - start_time) / num_trials) * 1000

# Performance: Compare ground truth with reduced output

In [9]:
def evaluate_metrics(raw_sim, reduced_sim, gt_k=50, test_k=10):
    num_queries = raw_sim.shape[0]
    prec, rec, map_score = 0.0, 0.0, 0.0
    
    for i in range(num_queries):
        raw_ordered = np.argsort(raw_sim[i])[-(gt_k+1):-1][::-1]
        gt_set = set(raw_ordered)
        
        red_ordered = np.argsort(reduced_sim[i])[-(test_k+1):-1][::-1]
        retrieved_k = red_ordered[:test_k]
        
        hits = len(set(retrieved_k).intersection(gt_set))
        prec += hits / test_k
        rec += hits / gt_k
        
        ap, current_hits = 0.0, 0
        for rank, item_idx in enumerate(retrieved_k):
            if item_idx in gt_set:
                current_hits += 1
                ap += current_hits / (rank + 1.0)
        if len(gt_set) > 0:
            map_score += ap / min(len(gt_set), test_k)
            
    return {
        "Precision@10": (prec/num_queries)*100, 
        "Recall@10": (rec/num_queries)*100, 
        "mAP@10": (map_score/num_queries)*100
    }

# Run Pipeline

In [12]:
def run_master_pipeline(modality, model_name, reducer_name="PCA"):
    print(f"Running {reducer_name} Pipeline for {model_name.upper()} ({modality})")
    
    raw_matrix = load_raw_matrix(modality, model_name)
    max_dim = raw_matrix.shape[1]
    
    raw_norm = normalize_matrix(raw_matrix)
    raw_sim = cosine_similarity(raw_norm, raw_norm)
    raw_speed_ms = measure_retrieval_speed(raw_matrix)
    
    master_results = [{
        "Model": model_name, "Method": "RAW", "Dim": max_dim,
        "mAP@10": 100.00, "Prec@10": 100.00, "Rec@10": 100.00,
        "Time (ms)": raw_speed_ms, "Speedup": "1.0x"
    }]
    
    reduction_func = apply_pca if reducer_name == "PCA" else apply_grp
    
    for dim in DIMENSIONS_TO_TEST:
        if dim >= max_dim: continue
        
        reduced_matrix = reduction_func(raw_matrix, dim)
        red_norm = normalize_matrix(reduced_matrix)
        red_sim = cosine_similarity(red_norm, red_norm)
        
        speed_ms = measure_retrieval_speed(reduced_matrix)
        speedup = raw_speed_ms / speed_ms if speed_ms > 0 else 0
        
        metrics = evaluate_metrics(raw_sim, red_sim)
        
        master_results.append({
            "Model": model_name, "Method": reducer_name, "Dim": dim,
            "mAP@10": metrics["mAP@10"], "Prec@10": metrics["Precision@10"], 
            "Rec@10": metrics["Recall@10"],
            "Time (ms)": speed_ms, "Speedup": f"{speedup:.1f}x"
        })
        
    df = pd.DataFrame(master_results).round(2)
    display(df)
    
    # Generate LaTeX
    latex_str = df.to_latex(index=False, float_format="%.2f", 
                            caption=f"{reducer_name} Reduction Performance for {model_name.upper()}",
                            label=f"tab:dim_red_{model_name}_{reducer_name}")
    print(latex_str)
    
    return df, raw_matrix, raw_sim

# XAI: Visualiser

In [10]:
def xai_visualize_reduction(raw_matrix, raw_sim, query_index=42, target_dim=32, top_k=5, reducer_name="PCA"):
    print(f"Generating XAI Visualizer ({reducer_name}-{target_dim})")
    
    reduction_func = apply_pca if reducer_name == "PCA" else apply_grp
    reduced_matrix = reduction_func(raw_matrix, target_dim)
    
    query_reduced = reduced_matrix[query_index].reshape(1, -1)
    sims_reduced = cosine_similarity(query_reduced, reduced_matrix)[0]
    
    top_indices_raw = raw_sim[query_index].argsort()[-(top_k+1):][::-1][1:]
    top_indices_reduced = sims_reduced.argsort()[-(top_k+1):][::-1][1:]
    
    fig, axes = plt.subplots(2, top_k + 1, figsize=(15, 5))
    plt.subplots_adjust(wspace=0.1, hspace=0.3)
    
    query_img = Image.open(IMAGE_PATHS[query_index]).convert('RGB')
    axes[0, 0].imshow(query_img); axes[0, 0].set_title("QUERY (RAW)", fontweight="bold"); axes[0, 0].axis("off")
    axes[1, 0].imshow(query_img); axes[1, 0].set_title(f"QUERY ({reducer_name}-{target_dim})", fontweight="bold"); axes[1, 0].axis("off")
    
    for i, idx in enumerate(top_indices_raw):
        axes[0, i+1].imshow(Image.open(IMAGE_PATHS[idx]).convert('RGB'))
        axes[0, i+1].set_title(f"RAW Rank {i+1}\nSim: {raw_sim[query_index][idx]:.2f}", fontsize=9)
        axes[0, i+1].axis("off")
        
    for i, idx in enumerate(top_indices_reduced):
        border_color = "green" if idx in top_indices_raw else "red"
        match_text = "(MATCH)" if idx in top_indices_raw else "(NEW)"
        axes[1, i+1].imshow(Image.open(IMAGE_PATHS[idx]).convert('RGB'))
        axes[1, i+1].set_title(f"Rank {i+1} {match_text}\nSim: {sims_reduced[idx]:.2f}", fontsize=9, color=border_color)
        axes[1, i+1].axis("off")
        
    plt.show()

# Run experiment

In [16]:
VISION_MODELS = ["resnet50", "mobilenet_v3", "vit", "deit", "clip_vision"]
TEXT_MODELS = ["rnn", "bert", "roberta", "gpt2", "clip_text"]
REDUCERS = ["PCA", "GRP"]

all_results = []

# 1. Run all Vision Models
print("STARTING VISION EXPERIMENTS")
for model in VISION_MODELS:
    for reducer in REDUCERS:
        try:
            df, _, _ = run_master_pipeline(modality="vision", model_name=model, reducer_name=reducer)
            all_results.append(df)
            message = f"✅ TFE Server: Dimension Reduction Notebook has finished running on {model}!"
            requests.post(f"https://ntfy.sh/{topic_name}",  data=message.encode(encoding='utf-8'))
        except FileNotFoundError:
            print(f"Skipping {model} - Matrix not found.")

message = "✅ TFE Server: Dimension Reduction Notebook has finished running on vision models!"
requests.post(f"https://ntfy.sh/{topic_name}",  data=message.encode(encoding='utf-8'))


# 2. Run all Text Models
print("\nSTARTING TEXT EXPERIMENTS")
for model in TEXT_MODELS:
    for reducer in REDUCERS:
        try:
            df, _, _ = run_master_pipeline(modality="text", model_name=model, reducer_name=reducer)
            all_results.append(df)
            message = f"✅ TFE Server: Dimension Reduction Notebook has finished running on {model}!"
            requests.post(f"https://ntfy.sh/{topic_name}",  data=message.encode(encoding='utf-8'))
        except FileNotFoundError:
            print(f"Skipping {model} - Matrix not found.")
            
message = "✅ TFE Server: Dimension Reduction Notebook has finished running on text models!"
requests.post(f"https://ntfy.sh/{topic_name}",  data=message.encode(encoding='utf-8'))

# 3. Save a Master CSV with absolutely everything
if all_results:
    final_master_df = pd.concat(all_results, ignore_index=True)
    final_master_df.to_csv(os.path.join(DATA_DIR, "MASTER_THESIS_RESULTS.csv"), index=False)
    print("\nAll experiments complete! Saved to MASTER_THESIS_RESULTS.csv")

STARTING VISION EXPERIMENTS
Running PCA Pipeline for RESNET50 (vision)

      Model Method   Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  resnet50    RAW  2048  100.00   100.00  100.00       8.14    1.0x
1  resnet50    PCA   512   98.40    98.63   19.73       5.18    1.6x
2  resnet50    PCA   256   97.54    97.96   19.59       3.22    2.5x
3  resnet50    PCA   128   95.95    96.66   19.33       0.77   10.6x
4  resnet50    PCA    64   92.51    93.91   18.78       0.71   11.5x
5  resnet50    PCA    32   84.06    87.34   17.47       0.63   12.9x
6  resnet50    PCA    16   67.24    74.24   14.85       0.65   12.6x

\begin{table}
\caption{PCA Reduction Performance for RESNET50}
\label{tab:dim_red_resnet50_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
resnet50 & RAW & 2048 & 100.00 & 100.00 & 100.00 & 8.14 & 1.0x \\
resnet50 & PCA & 512 & 98.40 & 98.63 & 19.73 & 5.18 & 1.6x \\
resnet50 & PCA & 256 & 97.54 & 97.96 & 19.59 & 3.22 & 2.5x \\
resnet50 & PCA & 128 & 95.95 & 96.66 & 19.33 & 0.77 & 10.6x \\
resnet50 & PCA & 64 & 92.51 & 93.91 & 18.78 & 0.71 & 11.5x \\
resnet50 & PCA & 32 & 84.06 & 87.34 & 17.47 & 0.63 & 12.9x \\
resnet50 & PCA & 16 & 67.24 & 74.24 & 14.85 & 0.65 & 12.6x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for RESNET50 (vision)

      Model Method   Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  resnet50    RAW  2048  100.00   100.00  100.00       7.84    1.0x
1  resnet50    GRP   512   98.94    99.15   19.83       2.91    2.7x
2  resnet50    GRP   256   95.82    96.70   19.34       4.25    1.8x
3  resnet50    GRP   128   85.13    88.43   17.68       0.56   14.1x
4  resnet50    GRP    64   68.50    75.39   15.08       0.42   18.5x
5  resnet50    GRP    32   41.98    52.60   10.52       0.35   22.3x
6  resnet50    GRP    16   21.30    32.07    6.41       0.32   24.8x

\begin{table}
\caption{GRP Reduction Performance for RESNET50}
\label{tab:dim_red_resnet50_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
resnet50 & RAW & 2048 & 100.00 & 100.00 & 100.00 & 7.84 & 1.0x \\
resnet50 & GRP & 512 & 98.94 & 99.15 & 19.83 & 2.91 & 2.7x \\
resnet50 & GRP & 256 & 95.82 & 96.70 & 19.34 & 4.25 & 1.8x \\
resnet50 & GRP & 128 & 85.13 & 88.43 & 17.68 & 0.56 & 14.1x \\
resnet50 & GRP & 64 & 68.50 & 75.39 & 15.08 & 0.42 & 18.5x \\
resnet50 & GRP & 32 & 41.98 & 52.60 & 10.52 & 0.35 & 22.3x \\
resnet50 & GRP & 16 & 21.30 & 32.07 & 6.41 & 0.32 & 24.8x \\
\bottomrule
\end{tabular}
\end{table}

Running PCA Pipeline for MOBILENET_V3 (vision)

          Model Method   Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  mobilenet_v3    RAW  1024  100.00   100.00  100.00       4.45    1.0x
1  mobilenet_v3    PCA   512   99.82    99.85   19.97       1.34    3.3x
2  mobilenet_v3    PCA   256   99.69    99.74   19.95       1.10    4.0x
3  mobilenet_v3    PCA   128   99.01    99.21   19.84       0.76    5.9x
4  mobilenet_v3    PCA    64   96.32    97.18   19.43       0.70    6.3x
5  mobilenet_v3    PCA    32   87.76    90.79   18.16       0.50    8.9x
6  mobilenet_v3    PCA    16   67.95    76.09   15.22       0.52    8.5x

\begin{table}
\caption{PCA Reduction Performance for MOBILENET_V3}
\label{tab:dim_red_mobilenet_v3_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
mobilenet_v3 & RAW & 1024 & 100.00 & 100.00 & 100.00 & 4.45 & 1.0x \\
mobilenet_v3 & PCA & 512 & 99.82 & 99.85 & 19.97 & 1.34 & 3.3x \\
mobilenet_v3 & PCA & 256 & 99.69 & 99.74 & 19.95 & 1.10 & 4.0x \\
mobilenet_v3 & PCA & 128 & 99.01 & 99.21 & 19.84 & 0.76 & 5.9x \\
mobilenet_v3 & PCA & 64 & 96.32 & 97.18 & 19.43 & 0.70 & 6.3x \\
mobilenet_v3 & PCA & 32 & 87.76 & 90.79 & 18.16 & 0.50 & 8.9x \\
mobilenet_v3 & PCA & 16 & 67.95 & 76.09 & 15.22 & 0.52 & 8.5x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for MOBILENET_V3 (vision)

          Model Method   Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  mobilenet_v3    RAW  1024  100.00   100.00  100.00       2.93    1.0x
1  mobilenet_v3    GRP   512   97.10    97.73   19.55       1.35    2.2x
2  mobilenet_v3    GRP   256   89.03    91.60   18.32       0.83    3.5x
3  mobilenet_v3    GRP   128   72.07    78.48   15.70       0.54    5.4x
4  mobilenet_v3    GRP    64   47.92    58.38   11.68       0.42    7.0x
5  mobilenet_v3    GRP    32   27.03    38.75    7.75       0.34    8.5x
6  mobilenet_v3    GRP    16   11.03    19.92    3.98       0.31    9.4x

\begin{table}
\caption{GRP Reduction Performance for MOBILENET_V3}
\label{tab:dim_red_mobilenet_v3_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
mobilenet_v3 & RAW & 1024 & 100.00 & 100.00 & 100.00 & 2.93 & 1.0x \\
mobilenet_v3 & GRP & 512 & 97.10 & 97.73 & 19.55 & 1.35 & 2.2x \\
mobilenet_v3 & GRP & 256 & 89.03 & 91.60 & 18.32 & 0.83 & 3.5x \\
mobilenet_v3 & GRP & 128 & 72.07 & 78.48 & 15.70 & 0.54 & 5.4x \\
mobilenet_v3 & GRP & 64 & 47.92 & 58.38 & 11.68 & 0.42 & 7.0x \\
mobilenet_v3 & GRP & 32 & 27.03 & 38.75 & 7.75 & 0.34 & 8.5x \\
mobilenet_v3 & GRP & 16 & 11.03 & 19.92 & 3.98 & 0.31 & 9.4x \\
\bottomrule
\end{tabular}
\end{table}

Running PCA Pipeline for VIT (vision)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0   vit    RAW  768  100.00   100.00  100.00       2.08    1.0x
1   vit    PCA  512   98.95    99.12   19.82       1.49    1.4x
2   vit    PCA  256   98.53    98.79   19.76       1.32    1.6x
3   vit    PCA  128   96.63    97.30   19.46       0.63    3.3x
4   vit    PCA   64   90.93    92.85   18.57       0.70    3.0x
5   vit    PCA   32   79.30    83.95   16.79       0.53    4.0x
6   vit    PCA   16   60.47    68.98   13.80       0.64    3.2x

\begin{table}
\caption{PCA Reduction Performance for VIT}
\label{tab:dim_red_vit_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
vit & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.08 & 1.0x \\
vit & PCA & 512 & 98.95 & 99.12 & 19.82 & 1.49 & 1.4x \\
vit & PCA & 256 & 98.53 & 98.79 & 19.76 & 1.32 & 1.6x \\
vit & PCA & 128 & 96.63 & 97.30 & 19.46 & 0.63 & 3.3x \\
vit & PCA & 64 & 90.93 & 92.85 & 18.57 & 0.70 & 3.0x \\
vit & PCA & 32 & 79.30 & 83.95 & 16.79 & 0.53 & 4.0x \\
vit & PCA & 16 & 60.47 & 68.98 & 13.80 & 0.64 & 3.2x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for VIT (vision)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0   vit    RAW  768  100.00   100.00  100.00       2.02    1.0x
1   vit    GRP  512   95.82    96.56   19.31       1.36    1.5x
2   vit    GRP  256   88.64    90.82   18.16       0.81    2.5x
3   vit    GRP  128   74.51    79.26   15.85       0.54    3.7x
4   vit    GRP   64   54.90    62.26   12.45       0.42    4.8x
5   vit    GRP   32   35.96    44.69    8.94       0.35    5.8x
6   vit    GRP   16   19.76    28.21    5.64       0.31    6.5x

\begin{table}
\caption{GRP Reduction Performance for VIT}
\label{tab:dim_red_vit_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
vit & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.02 & 1.0x \\
vit & GRP & 512 & 95.82 & 96.56 & 19.31 & 1.36 & 1.5x \\
vit & GRP & 256 & 88.64 & 90.82 & 18.16 & 0.81 & 2.5x \\
vit & GRP & 128 & 74.51 & 79.26 & 15.85 & 0.54 & 3.7x \\
vit & GRP & 64 & 54.90 & 62.26 & 12.45 & 0.42 & 4.8x \\
vit & GRP & 32 & 35.96 & 44.69 & 8.94 & 0.35 & 5.8x \\
vit & GRP & 16 & 19.76 & 28.21 & 5.64 & 0.31 & 6.5x \\
\bottomrule
\end{tabular}
\end{table}

Running PCA Pipeline for DEIT (vision)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  deit    RAW  768  100.00   100.00  100.00       2.16    1.0x
1  deit    PCA  512   99.95    99.96   19.99       1.35    1.6x
2  deit    PCA  256   99.75    99.81   19.96       1.09    2.0x
3  deit    PCA  128   98.55    98.84   19.77       0.78    2.8x
4  deit    PCA   64   93.33    94.84   18.97       0.72    3.0x
5  deit    PCA   32   80.28    84.98   16.99       0.56    3.8x
6  deit    PCA   16   58.73    67.76   13.55       0.59    3.7x

\begin{table}
\caption{PCA Reduction Performance for DEIT}
\label{tab:dim_red_deit_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
deit & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.16 & 1.0x \\
deit & PCA & 512 & 99.95 & 99.96 & 19.99 & 1.35 & 1.6x \\
deit & PCA & 256 & 99.75 & 99.81 & 19.96 & 1.09 & 2.0x \\
deit & PCA & 128 & 98.55 & 98.84 & 19.77 & 0.78 & 2.8x \\
deit & PCA & 64 & 93.33 & 94.84 & 18.97 & 0.72 & 3.0x \\
deit & PCA & 32 & 80.28 & 84.98 & 16.99 & 0.56 & 3.8x \\
deit & PCA & 16 & 58.73 & 67.76 & 13.55 & 0.59 & 3.7x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for DEIT (vision)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  deit    RAW  768  100.00   100.00  100.00       2.03    1.0x
1  deit    GRP  512   95.45    96.41   19.28       1.34    1.5x
2  deit    GRP  256   85.38    88.57   17.71       0.89    2.3x
3  deit    GRP  128   66.42    73.26   14.65       0.55    3.7x
4  deit    GRP   64   44.55    54.33   10.87       0.42    4.9x
5  deit    GRP   32   22.61    32.66    6.53       0.35    5.9x
6  deit    GRP   16   12.34    20.42    4.08       0.31    6.5x

\begin{table}
\caption{GRP Reduction Performance for DEIT}
\label{tab:dim_red_deit_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
deit & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.03 & 1.0x \\
deit & GRP & 512 & 95.45 & 96.41 & 19.28 & 1.34 & 1.5x \\
deit & GRP & 256 & 85.38 & 88.57 & 17.71 & 0.89 & 2.3x \\
deit & GRP & 128 & 66.42 & 73.26 & 14.65 & 0.55 & 3.7x \\
deit & GRP & 64 & 44.55 & 54.33 & 10.87 & 0.42 & 4.9x \\
deit & GRP & 32 & 22.61 & 32.66 & 6.53 & 0.35 & 5.9x \\
deit & GRP & 16 & 12.34 & 20.42 & 4.08 & 0.31 & 6.5x \\
\bottomrule
\end{tabular}
\end{table}

Running PCA Pipeline for CLIP_VISION (vision)

         Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  clip_vision    RAW  768  100.00   100.00  100.00       2.05    1.0x
1  clip_vision    PCA  512   98.86    99.09   19.82       1.44    1.4x
2  clip_vision    PCA  256   98.54    98.85   19.77       0.91    2.2x
3  clip_vision    PCA  128   97.40    97.94   19.59       0.52    4.0x
4  clip_vision    PCA   64   94.60    95.87   19.17       0.64    3.2x
5  clip_vision    PCA   32   87.60    90.66   18.13       0.56    3.6x
6  clip_vision    PCA   16   73.45    80.29   16.06       0.70    2.9x

\begin{table}
\caption{PCA Reduction Performance for CLIP_VISION}
\label{tab:dim_red_clip_vision_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
clip_vision & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.05 & 1.0x \\
clip_vision & PCA & 512 & 98.86 & 99.09 & 19.82 & 1.44 & 1.4x \\
clip_vision & PCA & 256 & 98.54 & 98.85 & 19.77 & 0.91 & 2.2x \\
clip_vision & PCA & 128 & 97.40 & 97.94 & 19.59 & 0.52 & 4.0x \\
clip_vision & PCA & 64 & 94.60 & 95.87 & 19.17 & 0.64 & 3.2x \\
clip_vision & PCA & 32 & 87.60 & 90.66 & 18.13 & 0.56 & 3.6x \\
clip_vision & PCA & 16 & 73.45 & 80.29 & 16.06 & 0.70 & 2.9x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for CLIP_VISION (vision)

         Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  clip_vision    RAW  768  100.00   100.00  100.00       1.98    1.0x
1  clip_vision    GRP  512   98.92    99.14   19.83       1.34    1.5x
2  clip_vision    GRP  256   95.16    96.16   19.23       0.81    2.4x
3  clip_vision    GRP  128   83.75    87.59   17.52       0.55    3.6x
4  clip_vision    GRP   64   65.67    73.22   14.64       0.41    4.8x
5  clip_vision    GRP   32   39.59    50.90   10.18       0.34    5.8x
6  clip_vision    GRP   16   18.79    28.97    5.79       0.31    6.4x

\begin{table}
\caption{GRP Reduction Performance for CLIP_VISION}
\label{tab:dim_red_clip_vision_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
clip_vision & RAW & 768 & 100.00 & 100.00 & 100.00 & 1.98 & 1.0x \\
clip_vision & GRP & 512 & 98.92 & 99.14 & 19.83 & 1.34 & 1.5x \\
clip_vision & GRP & 256 & 95.16 & 96.16 & 19.23 & 0.81 & 2.4x \\
clip_vision & GRP & 128 & 83.75 & 87.59 & 17.52 & 0.55 & 3.6x \\
clip_vision & GRP & 64 & 65.67 & 73.22 & 14.64 & 0.41 & 4.8x \\
clip_vision & GRP & 32 & 39.59 & 50.90 & 10.18 & 0.34 & 5.8x \\
clip_vision & GRP & 16 & 18.79 & 28.97 & 5.79 & 0.31 & 6.4x \\
\bottomrule
\end{tabular}
\end{table}


STARTING TEXT EXPERIMENTS
Running PCA Pipeline for RNN (text)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0   rnn    RAW  768  100.00   100.00  100.00       2.05    1.0x
1   rnn    PCA  512   95.06    96.02   19.20       1.54    1.3x
2   rnn    PCA  256   95.00    95.94   19.19       1.05    1.9x
3   rnn    PCA  128   94.46    95.48   19.09       0.78    2.6x
4   rnn    PCA   64   89.88    91.80   18.36       0.58    3.5x
5   rnn    PCA   32   77.45    82.35   16.47       0.49    4.2x
6   rnn    PCA   16   59.99    68.50   13.70       0.55    3.7x

\begin{table}
\caption{PCA Reduction Performance for RNN}
\label{tab:dim_red_rnn_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
rnn & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.05 & 1.0x \\
rnn & PCA & 512 & 95.06 & 96.02 & 19.20 & 1.54 & 1.3x \\
rnn & PCA & 256 & 95.00 & 95.94 & 19.19 & 1.05 & 1.9x \\
rnn & PCA & 128 & 94.46 & 95.48 & 19.09 & 0.78 & 2.6x \\
rnn & PCA & 64 & 89.88 & 91.80 & 18.36 & 0.58 & 3.5x \\
rnn & PCA & 32 & 77.45 & 82.35 & 16.47 & 0.49 & 4.2x \\
rnn & PCA & 16 & 59.99 & 68.50 & 13.70 & 0.55 & 3.7x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for RNN (text)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0   rnn    RAW  768  100.00   100.00  100.00       1.98    1.0x
1   rnn    GRP  512   98.48    98.76   19.75       1.94    1.0x
2   rnn    GRP  256   95.56    96.45   19.29       0.82    2.4x
3   rnn    GRP  128   86.31    89.25   17.85       0.54    3.6x
4   rnn    GRP   64   73.80    79.14   15.83       0.42    4.7x
5   rnn    GRP   32   52.03    61.24   12.25       0.34    5.8x
6   rnn    GRP   16   29.33    39.76    7.95       0.31    6.4x

\begin{table}
\caption{GRP Reduction Performance for RNN}
\label{tab:dim_red_rnn_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
rnn & RAW & 768 & 100.00 & 100.00 & 100.00 & 1.98 & 1.0x \\
rnn & GRP & 512 & 98.48 & 98.76 & 19.75 & 1.94 & 1.0x \\
rnn & GRP & 256 & 95.56 & 96.45 & 19.29 & 0.82 & 2.4x \\
rnn & GRP & 128 & 86.31 & 89.25 & 17.85 & 0.54 & 3.6x \\
rnn & GRP & 64 & 73.80 & 79.14 & 15.83 & 0.42 & 4.7x \\
rnn & GRP & 32 & 52.03 & 61.24 & 12.25 & 0.34 & 5.8x \\
rnn & GRP & 16 & 29.33 & 39.76 & 7.95 & 0.31 & 6.4x \\
\bottomrule
\end{tabular}
\end{table}

Running PCA Pipeline for BERT (text)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  bert    RAW  768  100.00   100.00  100.00       2.55    1.0x
1  bert    PCA  512   74.33    80.38   16.07       1.51    1.7x
2  bert    PCA  256   74.62    80.66   16.13       1.25    2.0x
3  bert    PCA  128   75.10    81.04   16.21       0.82    3.1x
4  bert    PCA   64   75.80    81.55   16.31       0.73    3.5x
5  bert    PCA   32   76.93    82.34   16.47       0.59    4.4x
6  bert    PCA   16   78.08    83.33   16.67       0.55    4.6x

\begin{table}
\caption{PCA Reduction Performance for BERT}
\label{tab:dim_red_bert_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
bert & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.55 & 1.0x \\
bert & PCA & 512 & 74.33 & 80.38 & 16.07 & 1.51 & 1.7x \\
bert & PCA & 256 & 74.62 & 80.66 & 16.13 & 1.25 & 2.0x \\
bert & PCA & 128 & 75.10 & 81.04 & 16.21 & 0.82 & 3.1x \\
bert & PCA & 64 & 75.80 & 81.55 & 16.31 & 0.73 & 3.5x \\
bert & PCA & 32 & 76.93 & 82.34 & 16.47 & 0.59 & 4.4x \\
bert & PCA & 16 & 78.08 & 83.33 & 16.67 & 0.55 & 4.6x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for BERT (text)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  bert    RAW  768  100.00   100.00  100.00       1.97    1.0x
1  bert    GRP  512  100.00   100.00   20.00       1.38    1.4x
2  bert    GRP  256   99.90    99.92   19.98       0.82    2.4x
3  bert    GRP  128   99.07    99.24   19.85       0.54    3.7x
4  bert    GRP   64   96.89    97.58   19.51       0.42    4.7x
5  bert    GRP   32   84.64    88.69   17.74       0.35    5.7x
6  bert    GRP   16   61.05    70.72   14.14       0.31    6.4x

\begin{table}
\caption{GRP Reduction Performance for BERT}
\label{tab:dim_red_bert_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
bert & RAW & 768 & 100.00 & 100.00 & 100.00 & 1.97 & 1.0x \\
bert & GRP & 512 & 100.00 & 100.00 & 20.00 & 1.38 & 1.4x \\
bert & GRP & 256 & 99.90 & 99.92 & 19.98 & 0.82 & 2.4x \\
bert & GRP & 128 & 99.07 & 99.24 & 19.85 & 0.54 & 3.7x \\
bert & GRP & 64 & 96.89 & 97.58 & 19.51 & 0.42 & 4.7x \\
bert & GRP & 32 & 84.64 & 88.69 & 17.74 & 0.35 & 5.7x \\
bert & GRP & 16 & 61.05 & 70.72 & 14.14 & 0.31 & 6.4x \\
\bottomrule
\end{tabular}
\end{table}

Running PCA Pipeline for ROBERTA (text)

     Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  roberta    RAW  768  100.00   100.00  100.00       2.10    1.0x
1  roberta    PCA  512   86.06    89.39   17.88       1.42    1.5x
2  roberta    PCA  256   86.11    89.42   17.88       0.99    2.1x
3  roberta    PCA  128   85.80    89.24   17.85       0.82    2.6x
4  roberta    PCA   64   84.31    88.13   17.62       0.55    3.8x
5  roberta    PCA   32   79.80    84.94   16.99       0.68    3.1x
6  roberta    PCA   16   67.32    75.63   15.12       0.61    3.4x

\begin{table}
\caption{PCA Reduction Performance for ROBERTA}
\label{tab:dim_red_roberta_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
roberta & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.10 & 1.0x \\
roberta & PCA & 512 & 86.06 & 89.39 & 17.88 & 1.42 & 1.5x \\
roberta & PCA & 256 & 86.11 & 89.42 & 17.88 & 0.99 & 2.1x \\
roberta & PCA & 128 & 85.80 & 89.24 & 17.85 & 0.82 & 2.6x \\
roberta & PCA & 64 & 84.31 & 88.13 & 17.62 & 0.55 & 3.8x \\
roberta & PCA & 32 & 79.80 & 84.94 & 16.99 & 0.68 & 3.1x \\
roberta & PCA & 16 & 67.32 & 75.63 & 15.12 & 0.61 & 3.4x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for ROBERTA (text)

     Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  roberta    RAW  768  100.00   100.00  100.00       1.97    1.0x
1  roberta    GRP  512   99.87    99.89   19.98       1.34    1.5x
2  roberta    GRP  256   98.54    98.84   19.77       0.81    2.4x
3  roberta    GRP  128   94.43    95.72   19.14       0.54    3.6x
4  roberta    GRP   64   79.81    84.72   16.94       0.42    4.7x
5  roberta    GRP   32   58.55    67.95   13.59       0.35    5.7x
6  roberta    GRP   16   27.67    40.02    8.00       0.31    6.4x

\begin{table}
\caption{GRP Reduction Performance for ROBERTA}
\label{tab:dim_red_roberta_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
roberta & RAW & 768 & 100.00 & 100.00 & 100.00 & 1.97 & 1.0x \\
roberta & GRP & 512 & 99.87 & 99.89 & 19.98 & 1.34 & 1.5x \\
roberta & GRP & 256 & 98.54 & 98.84 & 19.77 & 0.81 & 2.4x \\
roberta & GRP & 128 & 94.43 & 95.72 & 19.14 & 0.54 & 3.6x \\
roberta & GRP & 64 & 79.81 & 84.72 & 16.94 & 0.42 & 4.7x \\
roberta & GRP & 32 & 58.55 & 67.95 & 13.59 & 0.35 & 5.7x \\
roberta & GRP & 16 & 27.67 & 40.02 & 8.00 & 0.31 & 6.4x \\
\bottomrule
\end{tabular}
\end{table}

Running PCA Pipeline for GPT2 (text)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  gpt2    RAW  768  100.00   100.00  100.00       2.07    1.0x
1  gpt2    PCA  512   63.90    71.93   14.38       1.58    1.3x
2  gpt2    PCA  256   64.19    72.19   14.44       1.05    2.0x
3  gpt2    PCA  128   64.60    72.51   14.50       0.80    2.6x
4  gpt2    PCA   64   65.35    73.17   14.63       0.64    3.2x
5  gpt2    PCA   32   66.03    73.73   14.74       0.64    3.2x
6  gpt2    PCA   16   66.71    74.19   14.84       0.56    3.7x

\begin{table}
\caption{PCA Reduction Performance for GPT2}
\label{tab:dim_red_gpt2_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
gpt2 & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.07 & 1.0x \\
gpt2 & PCA & 512 & 63.90 & 71.93 & 14.38 & 1.58 & 1.3x \\
gpt2 & PCA & 256 & 64.19 & 72.19 & 14.44 & 1.05 & 2.0x \\
gpt2 & PCA & 128 & 64.60 & 72.51 & 14.50 & 0.80 & 2.6x \\
gpt2 & PCA & 64 & 65.35 & 73.17 & 14.63 & 0.64 & 3.2x \\
gpt2 & PCA & 32 & 66.03 & 73.73 & 14.74 & 0.64 & 3.2x \\
gpt2 & PCA & 16 & 66.71 & 74.19 & 14.84 & 0.56 & 3.7x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for GPT2 (text)

  Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  gpt2    RAW  768  100.00   100.00  100.00       2.02    1.0x
1  gpt2    GRP  512  100.00   100.00   20.00       1.40    1.4x
2  gpt2    GRP  256   99.96    99.96   19.99       0.84    2.4x
3  gpt2    GRP  128   99.54    99.65   19.93       0.54    3.7x
4  gpt2    GRP   64   96.56    97.36   19.47       0.42    4.9x
5  gpt2    GRP   32   87.72    90.93   18.18       0.35    5.8x
6  gpt2    GRP   16   57.03    67.52   13.50       0.31    6.5x

\begin{table}
\caption{GRP Reduction Performance for GPT2}
\label{tab:dim_red_gpt2_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
gpt2 & RAW & 768 & 100.00 & 100.00 & 100.00 & 2.02 & 1.0x \\
gpt2 & GRP & 512 & 100.00 & 100.00 & 20.00 & 1.40 & 1.4x \\
gpt2 & GRP & 256 & 99.96 & 99.96 & 19.99 & 0.84 & 2.4x \\
gpt2 & GRP & 128 & 99.54 & 99.65 & 19.93 & 0.54 & 3.7x \\
gpt2 & GRP & 64 & 96.56 & 97.36 & 19.47 & 0.42 & 4.9x \\
gpt2 & GRP & 32 & 87.72 & 90.93 & 18.18 & 0.35 & 5.8x \\
gpt2 & GRP & 16 & 57.03 & 67.52 & 13.50 & 0.31 & 6.5x \\
\bottomrule
\end{tabular}
\end{table}

Running PCA Pipeline for CLIP_TEXT (text)

       Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  clip_text    RAW  512  100.00   100.00  100.00       1.40    1.0x
1  clip_text    PCA  256   99.58    99.65   19.93       1.08    1.3x
2  clip_text    PCA  128   99.15    99.31   19.86       0.56    2.5x
3  clip_text    PCA   64   97.11    97.77   19.55       0.61    2.3x
4  clip_text    PCA   32   88.83    91.59   18.32       0.34    4.1x
5  clip_text    PCA   16   71.80    78.88   15.77       0.52    2.7x

\begin{table}
\caption{PCA Reduction Performance for CLIP_TEXT}
\label{tab:dim_red_clip_text_PCA}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
clip_text & RAW & 512 & 100.00 & 100.00 & 100.00 & 1.40 & 1.0x \\
clip_text & PCA & 256 & 99.58 & 99.65 & 19.93 & 1.08 & 1.3x \\
clip_text & PCA & 128 & 99.15 & 99.31 & 19.86 & 0.56 & 2.5x \\
clip_text & PCA & 64 & 97.11 & 97.77 & 19.55 & 0.61 & 2.3x \\
clip_text & PCA & 32 & 88.83 & 91.59 & 18.32 & 0.34 & 4.1x \\
clip_text & PCA & 16 & 71.80 & 78.88 & 15.77 & 0.52 & 2.7x \\
\bottomrule
\end{tabular}
\end{table}

Running GRP Pipeline for CLIP_TEXT (text)

       Model Method  Dim  mAP@10  Prec@10  Rec@10  Time (ms) Speedup
0  clip_text    RAW  512  100.00   100.00  100.00       1.33    1.0x
1  clip_text    GRP  256   97.81    98.23   19.64       0.85    1.6x
2  clip_text    GRP  128   91.81    93.58   18.72       0.54    2.4x
3  clip_text    GRP   64   74.79    80.35   16.07       0.42    3.1x
4  clip_text    GRP   32   50.19    59.99   12.00       0.35    3.9x
5  clip_text    GRP   16   28.28    39.82    7.96       0.31    4.3x

\begin{table}
\caption{GRP Reduction Performance for CLIP_TEXT}
\label{tab:dim_red_clip_text_GRP}
\begin{tabular}{llrrrrrl}
\toprule
Model & Method & Dim & mAP@10 & Prec@10 & Rec@10 & Time (ms) & Speedup \\
\midrule
clip_text & RAW & 512 & 100.00 & 100.00 & 100.00 & 1.33 & 1.0x \\
clip_text & GRP & 256 & 97.81 & 98.23 & 19.64 & 0.85 & 1.6x \\
clip_text & GRP & 128 & 91.81 & 93.58 & 18.72 & 0.54 & 2.4x \\
clip_text & GRP & 64 & 74.79 & 80.35 & 16.07 & 0.42 & 3.1x \\
clip_text & GRP & 32 & 50.19 & 59.99 & 12.00 & 0.35 & 3.9x \\
clip_text & GRP & 16 & 28.28 & 39.82 & 7.96 & 0.31 & 4.3x \\
\bottomrule
\end{tabular}
\end{table}


All experiments complete! Saved to MASTER_THESIS_RESULTS.csv